services:
  - type: web
    name: barfly-mystery-template
    env: node
    buildCommand: npm cache clean --force && npm install --no-audit --no-fund
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.18.1
